; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32@~4.4.0
board = esp32dev
framework = arduino
monitor_speed = 2000000
monitor_eol = LF
monitor_echo = yes
monitor_filters = send_on_enter
lib_deps = 
    asukiaaa/MPU9250_asukiaaa@^1.5.13
board_build.partitions = no_ota.csv
